# Generated by Django 2.1.2 on 2018-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docfile', models.FileField(blank=True, null=True, upload_to='server.DB_document/bytes/filename/mimetype')),
            ],
        ),
    ]
