# Generated by Django 2.1.2 on 2018-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_db_document_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_Document',
            new_name='DB_File',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='server.DB_File/bytes/filename/mimetype'),
        ),
    ]
