# Generated by Django 2.1 on 2018-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20181004_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_file',
            name='username',
            field=models.CharField(default='onkar', max_length=20),
            preserve_default=False,
        ),
    ]
