# Generated by Django 2.1.2 on 2018-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20181004_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='base_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
