# Generated by Django 2.1.2 on 2018-10-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_document_base_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_folder', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
