# Generated by Django 2.1 on 2018-10-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_db_file_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='username',
            field=models.CharField(default='onkar', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db_file',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
