# Generated by Django 2.1 on 2018-10-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_folder'),
        ('server', '0008_auto_20181012_1956'),
    ]

    operations = [
    ]
