# Generated by Django 2.1.2 on 2018-10-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20181012_1956'),
        ('server', '0008_folder'),
    ]

    operations = [
    ]
