# Generated by Django 2.1 on 2018-10-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_merge_20181022_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='username',
            field=models.CharField(default='onkar', max_length=150),
            preserve_default=False,
        ),
    ]
