# Generated by Django 2.1.2 on 2018-10-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_folder_username'),
        ('server', '0009_merge_20181022_1414'),
    ]

    operations = [
    ]
