# Generated by Django 2.1.2 on 2018-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_merge_20181027_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='md5sum',
            field=models.CharField(default='default null', max_length=255),
            preserve_default=False,
        ),
    ]
